# Generated by Django 4.1.3 on 2023-01-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0005_nse_setting_quantity_bn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nse_setting',
            name='quantity_bn',
        ),
    ]
