# Generated by Django 4.1.3 on 2023-01-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0007_nse_setting_quantity_bn'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_detail',
            name='orderid',
            field=models.IntegerField(null=True),
        ),
    ]
