# Generated by Django 4.1.3 on 2023-01-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0008_stock_detail_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_detail',
            name='orderid',
            field=models.FloatField(null=True),
        ),
    ]
