# Generated by Django 4.1.3 on 2023-01-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0009_alter_stock_detail_orderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='dropdown_stock_name_put',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pcr', models.FloatField(null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('PE_CE_diffrent', models.BooleanField(default=False)),
            ],
        ),
    ]
