# Generated by Django 4.1.3 on 2023-01-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0010_dropdown_stock_name_put'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_detail',
            name='buy_pcr',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock_detail',
            name='sell_pcr',
            field=models.FloatField(null=True),
        ),
    ]
